### PR TITLE
Update citation in SAM metric

### PR DESCRIPTION
**Pull request by vumichien**
## What does this PR do?

Fixes #885 add a citation

## Before submitting

- [x] Was this **discussed/approved** via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/metrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to **update the docs**?
- [x] Did you write any new **necessary tests**?

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
can you pls rather just add the citation in #885 instead of creating a new PR?

**Comment by vumichien** [comment]
Sorry, my mistake. Thank you for closing this PR

**Comment by Borda** [comment]
> Sorry, my mistake. Thank you for closing this PR

already cherry-picked the needed commit to the original PR :)

**Comment by vumichien** [comment]
Thank you so much

**Pull request closed without merging**
