### PR TITLE
Fixed bug in computing map metric for images with either no ground tr…

### LINKED ISSUE #794: MeanAveragePrecision incorrect calculations when predictions are empty
## 🐛 Bug

There seem to be some strange results when an image contains GTs but no predictions. This image is not considered when summarizing the results from all images. I've created a test to illustrate this

#### Code sample

```python
@pytest.mark.skipif(_pytest_condition, reason="test requires that torchvision=>0.8.0 is installed")
def test_one_correct_one_missing_prediction():
    """Test one correct prediction and one missing prediction"""
    metric = MeanAveragePrecision()

    preds = [
        dict(
            boxes=torch.Tensor([[214.1500, 41.2900, 562.4100, 285.0700]]),
            scores=torch.Tensor([0.5]),
            labels=torch.IntTensor([4]),
        ),
        dict(
            boxes=torch.Tensor([]),
            scores=torch.Tensor([]),
            labels=torch.IntTensor([]), # Empty prediction
        ),
    ]
    gts = [
        dict(boxes=torch.Tensor([[214.1500, 41.2900, 562.4100, 285.0700]]), labels=torch.IntTensor([4])),
        dict(boxes=torch.Tensor([[214.1500, 41.2900, 562.4100, 285.0700]]), labels=torch.IntTensor([4])), # Non-empty gt
    ]

    metric.update(preds, gts)
    result = metric.compute()
    # Since the second ground truth isn't found, the recall can not be 1. Thus mAP can not be 1
    assert result["map"] != 1
```

I believe that there is some error in `torchmetrics/detection/map.py MeanAveragePrecision._evaluate_image()`.

```python
# in _evaluate_image

if len(gt_label_mask) == 0 or len(det_label_mask) == 0:
    return None
gt = gt[gt_label_mask]
det = det[det_label_mask]
if len(gt) == 0 and len(det) == 0:
    return None
```

When `len(det_label_mask) == 0` the function returns None, which will disregard that image in downstream calculations. I’d argue that the model should be “punished” if it doesn’t find the GT.
Another thing is that I think `len(gt) == 0` should be replaced with `gt.numel() == 0` since empty `len(gt)` evaluates to 1 if the the gts are empty.

I've experienced this on the latest version of torchmetrics=0.7.0.

### PR DESCRIPTION
**Pull request by mtailanian**
…uth or no prediction

## What does this PR do?

Fixes #794 

When either the prediction or the ground truth is empty, the image was not taken into account for the metric computation.
This PR fixes that, by returning proper values

## Before submitting

- [x] Was this **discussed/approved** via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/metrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to **update the docs**?
- [x] Did you write any new **necessary tests**?

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by mtailanian** [comment]
Hello guys, just wanted to check if you're expecting some changes from my side? Maybe I'm missing something? I read the guidelines but I'm not used to making contributions. Please let me know how should we proceed.

**Comment by Borda** [comment]
@SkafteNicki or @twsl mind have look... :rabbit: ^^

**Comment by twsl** [comment]
The change seems fine to me, but tests are missing. Mind adding them for validation, @mtailanian ?

**Comment by mtailanian** [comment]
Hi @SkafteNicki, I'm not sure I did what was expected, but I just added my unit tests to the specified file. Some of them were actually duplicated, so I just omitted them.

Thanks,
Matías

**Review by SkafteNicki — APPROVED** [review]

**Review by Borda — APPROVED** [review]

**Pull request merged**
