### PR TITLE
FBeta update

### PR DESCRIPTION
**Pull request by SkafteNicki**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to update the docs?   
- [x] Did you write any new necessary tests?  

## What does this PR do?
Fixes https://github.com/PyTorchLightning/metrics/issues/55
Fixes https://github.com/PyTorchLightning/metrics/issues/58

Updates the internals of fbeta metric to use the stats score metric internal (similar to precision/recall). In addition to standardizing the interface even more, it also adds support for:
* TopK calculates
* Average='samples' 
* `ignore_index` argument for ignoring specific classes
* `mdmc_average` for how to aggregate when working with multi dimensional tensors

When everything is standardized to using the stat score metric it will be easier to implement support for non-normalized input (see issue https://github.com/PyTorchLightning/metrics/issues/60 and https://github.com/PyTorchLightning/metrics/issues/74)

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by Borda — COMMENTED** [review]
could you use the shorten typing for `torch.Tensor`

**Review by Borda — APPROVED** [review]

**Comment by Borda** [comment]
@SkafteNicki mind check the failing tests :]

**Comment by SkafteNicki** [comment]
@Borda should be fixed now :]

**Comment by Borda** [comment]
cool, the last missing is docs, some formatting issue...

**Review by ananyahjha93 — APPROVED** [review]

**Pull request merged**
