### PR TITLE
Remove `get_num_classes` in `jaccard_index`

### PR DESCRIPTION
**Pull request by rusty1s**
## What does this PR do?

This PR removes the `get_num_classes` call in `jaccard_index`. This call is no longer required since the `num_classes` argument of `jaccard_index` is now mandatory. Since `get_num_classes` is not used anywhere else, I removed the function completely.

## Before submitting

- [x] Was this **discussed/approved** via Slack? (discussed with @SkafteNicki and @Borda)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/metrics/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to **update the docs**?
- [ ] Did you write any new **necessary tests**?

### CODE REVIEW

**Review by Borda — APPROVED** [review]
mind adding a record to changelog? :rabbit:

**Comment by rusty1s** [comment]
done :)

**Comment by rusty1s** [comment]
What's the reason for the failing CI? Anything I can do about it?

**Comment by Borda** [comment]
> What's the reason for the failing CI? Anything I can do about it?

well, atm seems there is some connection error so nothing related to this PR :/

**Review by justusschock — APPROVED** [review]

**Review by SkafteNicki — APPROVED** [review]

**Pull request merged**
