### PR TITLE
Remove deprecated code from image domain

### PR DESCRIPTION
**Pull request by SkafteNicki**
## What does this PR do?

Fixes part of #771

## Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to update the docs?
- [x] Did you write any new necessary tests?

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Review by Borda — APPROVED** [review]
add chlog with removal

**Comment by SkafteNicki** [comment]
@Borda integration test are failing due to `torchmetrics.PSNR` no longer being available and older lightning versions are referring to it

**Comment by Borda** [comment]
> @Borda integration test are failing due to `torchmetrics.PSNR` no longer being available and older lightning versions are referring to it

so shall we keep this deprecation?

**Review by justusschock — APPROVED** [review]

**Comment by justusschock** [comment]
Personally, wouldn't keep it. If we keep it, we should keep them all, I think and extend the deprecation phase. Which Lightning Version is it?

**Comment by Borda** [comment]
> If we keep it

you mean if we remove deprecated metrics, right?

**Pull request merged**
