### PR TITLE
Simplify metrics testing utils

### PR DESCRIPTION
**Pull request by maximsch2**
Replicating PR6209 from PyTorchLightning

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  

## What does this PR do?
Fixes # (issue).

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by SkafteNicki** [comment]
@maximsch2 something about the changes in this PR makes nearly all the test stuck, and they get cancelled after 35 min (probably the reason why it never got merged in lightning). Could you check it out?

**Review by tchaton — APPROVED** [review]
LGTM ! Thanks.

**Comment by Borda** [comment]
still failing, mind check what is happening, does it run for you locally?

**Comment by maximsch2** [comment]
It used to run locally in PT repo, let me repro it and update if needed.

**Review by SkafteNicki — APPROVED** [review]

**Pull request merged**
