### PR TITLE
Refactor Metric forward to use only a single update call

### PR DESCRIPTION
**Pull request by janvainer**
Refactor Metric forward to use only a single update call.  #126

### CODE REVIEW

**Comment by Borda** [comment]
@janvainer how is it going here? any progress or need a hand? 🐰

**Comment by janvainer** [comment]
Hi @Borda, I am waiting for more inputs on the API changes that would be required to make this PR work. Please check this [issue](https://github.com/PyTorchLightning/metrics/issues/126). Once the API changes are clear and approved, I will rework the PR.

**Comment by Borda** [comment]
@PyTorchLightning/core-metrics mind share your opinion on the API?

**Comment by SkafteNicki** [comment]
Closing. See comment https://github.com/PyTorchLightning/metrics/issues/126#issuecomment-826879944.

**Pull request closed without merging**
