### PR TITLE
Solve pesq test failures

### PR DESCRIPTION
**Pull request by quancs**
## What does this PR do?

see disscussions [here](https://github.com/PyTorchLightning/metrics/pull/717#issuecomment-1006069751)

## Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
What I found they mostly recommend reinstall NumPy and also it mostly connected with legacy `pycocotools`

**Comment by quancs** [comment]
> What I found they mostly recommend reinstall NumPy and also it mostly connected with legacy `pycocotools`

I think both is OK. Numpy installed twice during the environment setup. While during the twice installation, pesq is compiled on the first numpy version (newer), so it cannot be loaded after installing the second numpy. Reinstalling pesq can make pesq get compiled on the later installed numpy

**Comment by quancs** [comment]
@Borda Can this be merged? ^^

**Comment by Borda** [comment]
> > What I found they mostly recommend reinstall NumPy and also it mostly connected with legacy `pycocotools`
> 
> I think both is OK. Numpy installed twice during the environment setup. While during the twice installation, pesq is compiled on the first numpy version (newer), so it cannot be loaded after installing the second numpy. Reinstalling pesq can make pesq get compiled on the later installed numpy

would it be the better way to find the minimal NumPy version feasible for `pesq` and `pycocotools` so there is no need to reinstall it and both then will be using the same NumPy package?

**Comment by Borda** [comment]
Ultimately the best would be implementing PESQ in-house so then `pesq` and `pycocotools` are installed only for tests and so in the same time...

**Review by Borda — APPROVED** [review]
switched to the fixed NumPy version
(turned out we had the same problem in past with PT 1.4 so setting the freeze to all PT versions)

**Pull request merged**
