### PR TITLE
update docstring links

### PR DESCRIPTION
**Pull request by XFarooqi**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

## What does this PR do?

This Pull Request will Fix issue #504 

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Yeah, I had fun finding the links in the docstrings and placing them in links.rst.

### CODE REVIEW

**Comment by Borda** [comment]
@XFarooqi cool, mind also use them in the codebase... :rabbit:

**Comment by XFarooqi** [comment]
> @XFarooqi cool, mind also use them in the codebase... 🐰

I am not sure what exactly you are asking
Can you please assist me on how to use them in codebase?

**Comment by Borda** [comment]
> Can you please assist me on how to use them in codebase?

sure, for example for the BLUE score you would replace 
```
`BLEU score <https://en.wikipedia.org/wiki/BLEU>\`_
```
 by 
```
`BLEU score\`_
```
 in
https://github.com/PyTorchLightning/metrics/blob/e6ad813867abbcb01d607057e7591c69a72cfc2d/torchmetrics/text/bleu.py#L29
and all other occurances

**Comment by XFarooqi** [comment]
> > Can you please assist me on how to use them in codebase?
> 
> sure, for example for the BLUE score you would replace
> 
> ```
> `BLEU score <https://en.wikipedia.org/wiki/BLEU>\`_
> ```
> 
> by
> 
> ```
> `BLEU score\`_
> ```
> 
> in
> https://github.com/PyTorchLightning/metrics/blob/e6ad813867abbcb01d607057e7591c69a72cfc2d/torchmetrics/text/bleu.py#L29
> 
> 
> and all other occurrences

## Task Solved
I have created another pull request #517 and all the requirements are fulfilled there.

**Comment by Borda** [comment]
> I have created another pull request #517 and all the requirements are fulfilled there.

So shall we close this one?

**Pull request closed without merging**
