### PR TITLE
make sure metriccollection is deterministic

### LINKED ISSUE #159: MetricCollection should enforce order when passed a dict
## 🐛 Bug

Not a clear bug yet, but just thinking about distributed metric computation, in here: https://github.com/PyTorchLightning/metrics/blob/53d570158a503497351ae45ec895ca44a0546068/torchmetrics/collections.py#L81
we should make sure to sort the names before the insert so that we insert things in the same order (ModuleDict is already OrderedDict otherwise). If we don't we will get deadlocks when doing distributed metric updates.

Additionally, we might want to enforce sorting when passed list/tuple, but that might be more on the user end.

### To Reproduce

On each of the workers, pass dictionary with same metrics but in different order, try compute and observe deadlock.

### PR DESCRIPTION
**Pull request by maximsch2**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?   
- [x] Did you write any new necessary tests?  

## What does this PR do?
Fixes #159 

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Review by Borda — APPROVED** [review]

**Review by tchaton — APPROVED** [review]
LGTM !

**Comment by Borda** [comment]
@SkafteNicki as some comments :]

**Review by SkafteNicki — CHANGES_REQUESTED** [review]
@maximsch2 we need to enforce the same change to when input is passed in as a list (and test for it)
Also we should probably note in the docstring that output will be sorted alphabetically.

**Comment by maximsch2** [comment]
Metrics in a List don't have names, so no good to sort them. And unlike dicts, lists are ordered, so it will be more on the user in that case IMO. My main concern is that `dict.items()` iteration might be different at different times

**Comment by SkafteNicki** [comment]
Metrics passed in as a list do have names, they are just added automatically. Should therefore have same problem as metrics passed in as dict.

**Comment by Borda** [comment]
@SkafteNicki are we set here? 🐰

**Review by SkafteNicki — APPROVED** [review]

**Comment by maximsch2** [comment]
I need to add a fix for list case as @SkafteNicki has suggested, but will do that as separate PR.

**Comment by SkafteNicki** [comment]
@maximsch2 after thinking about it, there is no need to it, as you said yourself the user has to explicitly construct a different list order per process for something to go wrong.

**Pull request merged**
