### PR TITLE
Metric sweeping

### PR DESCRIPTION
**Pull request by SkafteNicki**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

## What does this PR do?

Fixes https://github.com/PyTorchLightning/metrics/issues/148
Introduce the `higher_is_better` static property that determines if a metric is optimal when it is maximized (`True`), minimized (`False`) or this is undefined (`None`).
Still missing adding some metrics were I am not sure what the property should be.
cc: @maximsch2 

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by Borda** [comment]
I think it shall be property so it is not possible to change it, the same as is differentiable...
also, do we have another name candidate, this sounds a bit hacky to me... 
@PyTorchLightning/core-metrics @justusschock @maximsch2

**Comment by SkafteNicki** [comment]
Fine with this being a property instead.
Name was suggested by @maximsch2

**Comment by SkafteNicki** [comment]
@lucadiliello what is the correct value for all our retrieval metrics (you are the expert)?
Is a model optimal when they are maximized or minimized or is it not well defined?

**Comment by lucadiliello** [comment]
> @lucadiliello what is the correct value for all our retrieval metrics (you are the expert)?
> Is a model optimal when they are maximized or minimized or is it not well defined?

Hi @SkafteNicki , all retrieval metrics should have `higher_is_better=True` apart from FallOut, which should be minimised.

**Comment by Borda** [comment]
> Only reason I wanted this to be a class attribute was to give the user the possibility of actually getting this value even before the class was initialized.

that is a good point but in the same light why the `is_differentiable` would be needed first to be initialized?

we can ban certain attributes from being overwritten as for example:
```py
    def _ _setattr_ _(self, name, value):
        if name in ("higher_is_better", "is_diffrenetiable"):
            raise RuntimeError(f"Can't chnage const `{name}`."
        self._ _dict_ _[name] = value
```

**Comment by SkafteNicki** [comment]
> 
> 
> > Only reason I wanted this to be a class attribute was to give the user the possibility of actually getting this value even before the class was initialized.
> 
> that is a good point but in the same light why the `is_differentiable` would be needed first to be initialized?
> 
> we can ban certain attributes from being overwritten as for example:
> 
> ```python
>     def _ _setattr_ _(self, name, value):
>         if name in ("higher_is_better", "is_diffrenetiable"):
>             raise RuntimeError(f"Can't chnage const `{name}`."
>         self._ _dict_ _[name] = value
> ```

You are completely right. I think we should also change `is_differentiable` to be this way and it looks like a good solution to me :]

**Comment by SkafteNicki** [comment]
Anyone got a better name? On top of my head

* `higher_is_better`: options `True`, `False`, `None`
* `maximize` (or `minimize`): options `True`, `False`, `None`
* `direction` or `optim_direction`: options `maximize`, `minimize`, `None`
* ...

**Review by tchaton — APPROVED** [review]

**Review by Borda — APPROVED** [review]

**Comment by SkafteNicki** [comment]
@Borda please wait with merge, going to add the property to some more metrics

**Review by tchaton — APPROVED** [review]
LGTM !

**Comment by Borda** [comment]
@SkafteNicki mind check the failing tests on GPU?

**Pull request merged**
